### ISSUE TITLE
Build error on test_pitch

### ISSUE THREAD

**Issue by gunthercox** [cmusphinx/sphinxbase#21]
Following the instructions in the readme, I encountered a test failure on `test_pitch`  while running `make check`. I am currently building this on a ubuntu distribution if that makes a difference.

```traceback
make[5]: Entering directory '/home/gcox/GitHub/sphinxbase/test/unit/test_fe'
PASS: test_fe
*** stack smashing detected ***: /home/gcox/GitHub/sphinxbase/test/unit/test_fe/.libs/lt-test_pitch terminated
../../../test-driver: line 107: 31495 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: test_pitch
============================================================================
Testsuite summary for sphinxbase 5prealpha
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/unit/test_fe/test-suite.log
============================================================================
Makefile:688: recipe for target 'test-suite.log' failed
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory '/home/gcox/GitHub/sphinxbase/test/unit/test_fe'
Makefile:794: recipe for target 'check-TESTS' failed
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory '/home/gcox/GitHub/sphinxbase/test/unit/test_fe'
Makefile:874: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/gcox/GitHub/sphinxbase/test/unit/test_fe'
Makefile:391: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/gcox/GitHub/sphinxbase/test/unit'
Makefile:370: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/gcox/GitHub/sphinxbase/test'
Makefile:476: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
Let me know if there is any other information I can provide.

**Comment by mbait** [comment]
Thank you for reporting the issue! Please post the output of `uname -a` and the hash of the commit you are on while running the test.

**Comment by gunthercox** [comment]
**commit** `c6e3c0ddf4e8ed5195492b0a7476890dc127967e`
**uname -a** Linux Y40 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nshmyrev** [comment]
This is a known bug with fixed mode, sorry, you can ignore this test error. I'll try to fix it asap. Tracked here:

https://sourceforge.net/p/cmusphinx/bugs/445/

**Comment by gunthercox** [comment]
Thank you! Glad to know it can be ignored.

**Comment by kamalmeh** [comment]
Iam facing similar issue on fedora27.
FAIL: test-cepview.sh
FAIL: test-sphinx_fe-ctl.sh
FAIL: test-sphinx_fe-dct.sh
FAIL: test-sphinx_fe-dither-seed.sh
FAIL: test-sphinx_fe-logspec2cep.sh
FAIL: test-sphinx_fe-logspec.sh
FAIL: test-sphinx_fe.sh
FAIL: test-sphinx_fe-smoothspec.sh
FAIL: test-sphinx_jsgf2fsg.sh
PASS: test-sphinx_pitch.sh
============================================================================
Testsuite summary for sphinxbase 5prealpha
============================================================================
# TOTAL: 10
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0
============================================================================
See test/regression/test-suite.log
============================================================================
make[4]: *** [Makefile:562: test-suite.log] Error 1
make[4]: Leaving directory '/home/kh08603/sphinxbase/test/regression'
make[3]: *** [Makefile:670: check-TESTS] Error 2
make[3]: Leaving directory '/home/kh08603/sphinxbase/test/regression'
make[2]: *** [Makefile:803: check-am] Error 2
make[2]: Leaving directory '/home/kh08603/sphinxbase/test/regression'
make[1]: *** [Makefile:371: check-recursive] Error 1
make[1]: Leaving directory '/home/kh08603/sphinxbase/test'
make: *** [Makefile:478: check-recursive] Error 1

due to this I am not able to cimpile pocketsphinx on fedora27.
Could you please help?
[root@localhost sphinxbase]# uname -a
Linux localhost.localdomain 4.13.9-300.fc27.x86_64 #1 SMP Mon Oct 23 13:41:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kamalmeh** [comment]
This issue is was due to the package name sphinxbase-master. I modified in ontaining files in the package to resolve it.
