### ISSUE TITLE
Training Sphinx

### ISSUE THREAD

**Issue by danvilar** [cmusphinx/sphinxbase#31]
Hi! I've been wondering if it is possible and effective it would be to train sphinx using the large freely available audiobooks that we have on the internet. If it is, how would you suggest it would be the best approach?

Thanks

**Comment by nshmyrev** [comment]
Database of audiobooks ready for training is available here:

http://www.openslr.org/12/

You can train on it if you want, the default model already includes this data, so you won't gain much over default model. The model is described in publications here:

http://www.danielpovey.com/files/2015_icassp_librispeech.pdf

Our models for different languages also include audiobook data. 

The main problem with using this data is that the training is not transferable across domain. Audiobook data has little use for recognition of mobile or telephone or desktop data because the latter is corrupted with nonlinear noises caused by compression and echo. Audiobook voices and pronunciation are also quite different from normal people voices and pronunciation. In theory one can try to prepare multistyle training by emulating real-life data with audiobook data, but it's still a research problem and it is not very successful.
